// GENERATED by scripts/generate-provider-catalog.mjs — do not edit by hand.
// Source: @earendil-works/pi-ai 0.84.1 provider registry, curated to
// API-key providers reachable over Obsidian requestUrl. Rerun the script
// after upgrading pi-ai. See the script header for inclusion criteria.

/** Wire protocol our backends speak to this provider. */
export type ProviderKind = "openai-compat" | "anthropic" | "gemini";

export interface ProviderCatalogEntry {
  /** pi-ai provider id — also the settings/secret-store key. */
  id: string;
  name: string;
  kind: ProviderKind;
  /**
   * URL prefix per kind: openai-compat → +"/chat/completions",
   * anthropic → +"/v1/messages", gemini → +"/models/{model}:generateContent".
   */
  baseUrl: string;
  /** Cheapest listed model — recovery loops prefer cheap and fast. */
  defaultModel: string;
  keyPlaceholder: string;
}

/** Sentinel id for user-defined OpenAI-compatible endpoints. */
export const CUSTOM_PROVIDER_ID = "custom";

export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: "ant-ling",
    name: "Ant Ling",
    kind: "openai-compat",
    baseUrl: "https://api.ant-ling.com/v1",
    defaultModel: "Ling-2.6-flash",
    keyPlaceholder: "API key",
  },
  {
    id: "anthropic",
    name: "Anthropic API key",
    kind: "anthropic",
    baseUrl: "https://api.anthropic.com",
    defaultModel: "claude-sonnet-4-5",
    keyPlaceholder: "sk-ant-…",
  },
  {
    id: "baseten",
    name: "Baseten",
    kind: "openai-compat",
    baseUrl: "https://inference.baseten.co/v1",
    defaultModel: "openai/gpt-oss-120b",
    keyPlaceholder: "API key",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    kind: "openai-compat",
    baseUrl: "https://api.cerebras.ai/v1",
    defaultModel: "gpt-oss-120b",
    keyPlaceholder: "API key",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    kind: "openai-compat",
    baseUrl: "https://api.deepseek.com",
    defaultModel: "deepseek-chat",
    keyPlaceholder: "sk-…",
  },
  {
    id: "fireworks",
    name: "Fireworks",
    kind: "openai-compat",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    defaultModel: "accounts/fireworks/models/gpt-oss-20b",
    keyPlaceholder: "API key",
  },
  {
    id: "google",
    name: "Google",
    kind: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultModel: "gemini-2.5-flash",
    keyPlaceholder: "AIza…",
  },
  {
    id: "groq",
    name: "Groq",
    kind: "openai-compat",
    baseUrl: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.1-8b-instant",
    keyPlaceholder: "API key",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    kind: "openai-compat",
    baseUrl: "https://router.huggingface.co/v1",
    defaultModel: "zai-org/GLM-4.7-Flash",
    keyPlaceholder: "API key",
  },
  {
    id: "minimax",
    name: "MiniMax",
    kind: "anthropic",
    baseUrl: "https://api.minimax.io/anthropic",
    defaultModel: "MiniMax-M2.7",
    keyPlaceholder: "API key",
  },
  {
    id: "minimax-cn",
    name: "MiniMax CN",
    kind: "anthropic",
    baseUrl: "https://api.minimaxi.com/anthropic",
    defaultModel: "MiniMax-M2.7",
    keyPlaceholder: "API key",
  },
  {
    id: "mistral",
    name: "Mistral",
    kind: "openai-compat",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "labs-devstral-small-2512",
    keyPlaceholder: "API key",
  },
  {
    id: "moonshotai",
    name: "Moonshot AI",
    kind: "openai-compat",
    baseUrl: "https://api.moonshot.ai/v1",
    defaultModel: "kimi-k2-0711-preview",
    keyPlaceholder: "API key",
  },
  {
    id: "moonshotai-cn",
    name: "Moonshot AI CN",
    kind: "openai-compat",
    baseUrl: "https://api.moonshot.cn/v1",
    defaultModel: "kimi-k2-0711-preview",
    keyPlaceholder: "API key",
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    kind: "openai-compat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    defaultModel: "google/gemma-3-12b-it",
    keyPlaceholder: "API key",
  },
  {
    id: "openai",
    name: "OpenAI",
    kind: "openai-compat",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-5.5",
    keyPlaceholder: "sk-…",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    kind: "openai-compat",
    baseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "openrouter/auto",
    keyPlaceholder: "sk-or-…",
  },
  {
    id: "qwen-token-plan",
    name: "Qwen Token Plan",
    kind: "openai-compat",
    baseUrl: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    defaultModel: "deepseek-v3.2",
    keyPlaceholder: "API key",
  },
  {
    id: "qwen-token-plan-cn",
    name: "Qwen Token Plan CN",
    kind: "openai-compat",
    baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    defaultModel: "deepseek-v3.2",
    keyPlaceholder: "API key",
  },
  {
    id: "qwen-token-plan-individual",
    name: "Qwen Token Plan Individual",
    kind: "openai-compat",
    baseUrl: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    defaultModel: "deepseek-v4-flash-0731",
    keyPlaceholder: "API key",
  },
  {
    id: "together",
    name: "Together",
    kind: "openai-compat",
    baseUrl: "https://api.together.ai/v1",
    defaultModel: "openai/gpt-oss-20b",
    keyPlaceholder: "API key",
  },
  {
    id: "vercel-ai-gateway",
    name: "Vercel AI Gateway",
    kind: "openai-compat",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    defaultModel: "inclusionai/ling-3.0-tiny-free",
    keyPlaceholder: "API key",
  },
  {
    id: "xai",
    name: "xAI",
    kind: "openai-compat",
    baseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-build-0.1",
    keyPlaceholder: "API key",
  },
  {
    id: "xiaomi",
    name: "Xiaomi",
    kind: "openai-compat",
    baseUrl: "https://api.xiaomimimo.com/v1",
    defaultModel: "mimo-v2-flash",
    keyPlaceholder: "API key",
  },
  {
    id: "xiaomi-token-plan-ams",
    name: "Xiaomi Token Plan AMS",
    kind: "openai-compat",
    baseUrl: "https://token-plan-ams.xiaomimimo.com/v1",
    defaultModel: "mimo-v2-pro",
    keyPlaceholder: "API key",
  },
  {
    id: "xiaomi-token-plan-cn",
    name: "Xiaomi Token Plan CN",
    kind: "openai-compat",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
    defaultModel: "mimo-v2-pro",
    keyPlaceholder: "API key",
  },
  {
    id: "xiaomi-token-plan-sgp",
    name: "Xiaomi Token Plan SGP",
    kind: "openai-compat",
    baseUrl: "https://token-plan-sgp.xiaomimimo.com/v1",
    defaultModel: "mimo-v2-pro",
    keyPlaceholder: "API key",
  },
  {
    id: "zai",
    name: "Z.AI",
    kind: "openai-compat",
    baseUrl: "https://api.z.ai/api/coding/paas/v4",
    defaultModel: "glm-4.7",
    keyPlaceholder: "API key",
  },
  {
    id: "zai-coding-cn",
    name: "Z.AI Coding CN",
    kind: "openai-compat",
    baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    defaultModel: "glm-4.7",
    keyPlaceholder: "API key",
  },
];

export function catalogEntry(id: string): ProviderCatalogEntry | undefined {
  return PROVIDER_CATALOG.find((e) => e.id === id);
}
